[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_flags =
    '-DWIFI_SSID="${sysenv.WIFI_SSID}"'
    '-DWIFI_PASSWORD="${sysenv.WIFI_PASSWORD}"'
lib_deps =
    ESP32Async/ESPAsyncWebServer @ ^3.6.0
    ESP32Async/AsyncTCP @ ^3.3.2
    bblanchon/ArduinoJson @ ^7.3.1
